project_name: "PotionPanic"
default_status: "Backlog"
statuses: ["Backlog", "To Do", "In Progress", "Done"]
labels: []
definition_of_done: ["Tests pass", "Documentation updated", "No regressions introduced"]
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "rider"
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
filesystem_only: false
bypass_git_hooks: true
check_active_branches: false
active_branch_days: 10
task_prefix: "PP"
backlog_directory: "backlog"
